# Generated by Django 3.2.6 on 2021-08-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0002_facture'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.AlterField(
            model_name='user',
            name='factures',
            field=models.ManyToManyField(blank=True, to='Entities.Facture'),
        ),
    ]
