# Generated by Django 3.2.6 on 2021-08-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='factures',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.facture'),
            preserve_default=False,
        ),
    ]
