# Generated by Django 3.2.6 on 2021-08-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210830_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_activated',
            new_name='is_verified',
        ),
    ]
