# Generated by Django 3.2.6 on 2021-08-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('user_IP_address', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.PositiveIntegerField()),
                ('article_name', models.CharField(max_length=30)),
                ('article_category', models.CharField(max_length=256)),
                ('article_provider', models.CharField(max_length=30)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Article viewed',
                'verbose_name_plural': 'Articles viewed',
                'ordering': ['-timestamp'],
            },
        ),
    ]
