# Generated by Django 3.2.6 on 2021-08-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesviewed',
            old_name='ip_address',
            new_name='user_IP_address',
        ),
    ]
