# Generated by Django 3.2.6 on 2021-08-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_rename_ip_address_articlesviewed_user_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesviewed',
            old_name='user',
            new_name='username',
        ),
    ]
