# Generated by Django 3.2.6 on 2021-08-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_alter_objectviewed_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectviewed',
            old_name='object_id',
            new_name='article_id',
        ),
    ]
