# Generated by Django 3.2.6 on 2021-08-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0003_rename_user_articlesviewed_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesviewed',
            name='article_category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlesviewed',
            name='article_name',
            field=models.CharField(max_length=256),
        ),
    ]
