# Generated by Django 3.2.6 on 2021-08-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_objectviewed_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='provider',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
