# Generated by Django 3.2.6 on 2021-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_auto_20210819_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesviewed',
            name='article_category',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='articlesviewed',
            name='article_name',
            field=models.CharField(max_length=30),
        ),
    ]
