# Generated by Django 3.2.6 on 2021-08-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0005_objectviewed_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectviewed',
            old_name='provider',
            new_name='article_provider',
        ),
    ]
