# Generated by Django 3.2.6 on 2021-08-09 14:17

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('cin', models.CharField(blank=True, max_length=10, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_login', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCategorie', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('libelleCategorie', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ModeDeLivraison',
            fields=[
                ('idModeDeLivraison', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('libelleModeDeLivraison', models.CharField(max_length=50)),
                ('descriptionModeDeLivraison', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ModeDePaiement',
            fields=[
                ('idModeDePaiement', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('libelleModeDePaiement', models.CharField(max_length=50)),
                ('descriptionModeDePaiement', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idFacture', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('datePaiementFacture', models.DateTimeField(auto_now_add=True)),
                ('prixHtFacture', models.FloatField()),
                ('totalHtFacture', models.FloatField()),
                ('totalTtc', models.FloatField()),
                ('clientFacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entities.account')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idCommande', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dateAjoutCommande', models.DateTimeField(auto_now_add=True)),
                ('descriptionCommande', models.CharField(max_length=256)),
                ('modeDeLivraisonCommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entities.modedelivraison')),
                ('modeDePaiementCommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entities.modedepaiement')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('idArticle', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('imageArticle', models.ImageField(blank=True, null=True, upload_to='')),
                ('nomArticle', models.CharField(max_length=50)),
                ('descriptionArticle', models.CharField(max_length=256)),
                ('quantiteArticle', models.IntegerField()),
                ('prixArticle', models.FloatField()),
                ('dateAjoutArticle', models.DateTimeField(auto_now_add=True)),
                ('categorieArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entities.categorie')),
            ],
        ),
    ]
