# Generated by Django 3.2.6 on 2021-08-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
    ]
