# Generated by Django 3.2.6 on 2021-08-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bought', models.DateTimeField(auto_now_add=True)),
                ('ht_price', models.FloatField()),
                ('total_ht', models.FloatField()),
                ('total_ttc', models.FloatField()),
            ],
        ),
    ]
