# Generated by Django 3.2.6 on 2021-08-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0002_article_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categorieArticle',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='dateAjoutArticle',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='descriptionArticle',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='imageArticle',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='nomArticle',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='prixArticle',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='quantiteArticle',
            new_name='quantity',
        ),
    ]
