# Generated by Django 3.2.6 on 2021-08-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0003_auto_20210819_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='libelleCategorie',
            new_name='libelle',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='dateAjoutCommande',
            new_name='dateAjout',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='descriptionCommande',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='modeDeLivraisonCommande',
            new_name='modeDeLivraison',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='modeDePaiementCommande',
            new_name='modeDePaiement',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='clientFacture',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='datePaiementFacture',
            new_name='date_bought',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='prixHtFacture',
            new_name='ht_price',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='totalHtFacture',
            new_name='total_ht',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='totalTtc',
            new_name='total_ttc',
        ),
        migrations.RenameField(
            model_name='modedelivraison',
            old_name='descriptionModeDeLivraison',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='modedelivraison',
            old_name='libelleModeDeLivraison',
            new_name='libelle',
        ),
        migrations.RenameField(
            model_name='modedepaiement',
            old_name='descriptionModeDePaiement',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='modedepaiement',
            old_name='libelleModeDePaiement',
            new_name='libelle',
        ),
    ]
